import type { Metadata } from "next";
import '../globals.css'

export const metadata: Metadata = {
    title: "Tema 3",
    description: "Generated by create next app",
};

export const viewport = {
    initialScale: 1.0,
    width: "device-width",
    colorScheme: "light",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <div>{children}</div>;
}